export const firebaseApiKey = process.env.NEXT_PUBLIC_FIREBASE_APIKEY
export const firebaseAuthDomain = process.env.NEXT_PUBLIC_FIREBASE_AUTHDOMAIN
export const firebaseDatabaseURL = process.env.NEXT_PUBLIC_FIREBASE_DATABASEURL
export const firebaseProjectID = process.env.NEXT_PUBLIC_FIREBASE_PROJECTID
export const firebaseStorageBucket = process.env.NEXT_PUBLIC_FIREBASE_STORAGEBUCKET
export const firebaseMessagingInSender = process.env.NEXT_PUBLIC_FIREBASE_MESSAGINGSENDERID
export const firebaseAppID = process.env.NEXT_PUBLIC_FIREBASE_APPID
export const firebaseMeasurementID = process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENTID